### ISSUE TITLE
Script errors with: list indices must be integers or slices, not NoneType

### ISSUE THREAD

**Issue by bogski87** [prjblk/nessus-database-export#4]
Hello, 

I've been using your database export for a few hours and have got it working, it's very nice. However I've run into an issue and as a Python novice I'm reluctant to start messing around with the script itself. 

When i run the python script manually, i get the following error: 
```
Processing: ******** ******* **** 2nd Range
Inserting scan run: 178
Traceback (most recent call last):
  File "export.py", line 277, in <module>
    update_scans()
  File "export.py", line 274, in update_scans
    insert_scan_run(scan['id'], scan_run['history_id'])
  File "export.py", line 209, in insert_scan_run
    sev_count[vuln['severity']] += vuln['count']
TypeError: list indices must be integers or slices, not NoneType
```

After checking my database, i can see some info is inserted 
![image](https://user-images.githubusercontent.com/35738951/122903353-3b8a7300-d347-11eb-8c17-2601fb1a594c.png)

The tables above do contain data, but they only contain data for one "plugin" which related to the 2nd Range being processed. But if i query the nessus API in postman i can see additional scan data. I think the error above has caused the script to fail and stop processing giving me only the first result it finds. 

I've also noticed that stored procedures and views do not exist, when trying to follow some of the usage examples i get the error

`SQL Error [1305] [42000]: (conn=560697) PROCEDURE nessusdb.get_folder_results does not exist `

I'm not quite sure what is going on, I followed the instructions in the git repo. The main issue i had was connectivity issues with my sql user, I switched to root for now which partially works. 

Any ideas on what could be the cause? We'd love to get this working. 

Setup:

Ubuntu 18 x64
MariaDB (Docker container)

MariaDB and the Nessus export tool are both on the same ubuntu server. 

Thanks

PhilB

**Comment by Al538** [comment]
Hi.
I wrote https://github.com/eddiez9/nessus-database-export/issues/3
I just added a little check in lines 177-178 and 208-209:

```
for vuln in scan_run['vulnerabilities']:
    if vuln['severity'] != None:
        sev_count[vuln['severity']] += vuln['count']
```

**Comment by eddiez9** [comment]
Hi PhilB,

I've added the rcheck @Al538 mentions, hopefully that's resolved.

To use the stored procedures, you need to install them first (similar to how the schema.sql is installed). I've updated the project to include a dockerfile which sets up and configures a MySQL DB with the schema and stored procedures off the bat
